[package]
name = "report-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
nfm-common = { path = "../../nfm-common" }
nfm-controller = { path = "../../nfm-controller" }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }