[config]
# cgroup used to monitor network events.
cgroup=default
# provide the endpoint URL, or default to use the endpoint of the Network Flow Monitor service.
endpoint=default
# provide the region of the endpoint, or default to use the region retrieved from the local instance metadata service (IMSv2).
region=default
# aggregation interval in milliseconds (100-60000). Lower values give more granular data at higher CPU cost. Default 500
aggregate_msecs=default
# Maximum number of new sockets allowed per aggregate_msecs miliseconds. If default, set automatically proportional to system memory. range 256 - 20000
max_sock_props=default
