name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - name: Run tests
        run: cargo test --release
      - name: Run clipply
        run: cargo clippy -- -D warnings
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Check code coverage
        run: |
          BPF_OBJECT_PATH="${{ github.workspace }}/target/ebpf/bpfel-unknown-none/release/nfm-bpf" \
          cargo tarpaulin --ignore-tests \
          --workspace \
          --exclude nfm-bpf \
          --exclude-files '**/build.rs' \
          --out xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
