name: Performance Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  aws-perf-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Build agent
        run: cargo build --release

      - name: Build tcp-tester
        run: |
          cargo build --release --package tcp-tester

      - name: Configure AWS credentials
        id: aws-creds
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.PR_PERF_TEST_AWS_ROLE_ARN }}
          aws-region: ${{ secrets.PR_PERF_TEST_AWS_REGION }}
          mask-aws-account-id: true

      - name: Create EC2 instances
        if: steps.aws-creds.outcome == 'success'
        run: |
          cd load-generator
          chmod +x bin/*
          bin/create-instances --region ${{ secrets.PR_PERF_TEST_AWS_REGION }}

      - name: Run Performance tests on EC2 instances
        if: steps.aws-creds.outcome == 'success'
        run: |
          cd load-generator
          bin/invoke_test

      - name: Cleanup EC2 instances
        if: steps.aws-creds.outcome == 'success' && always()
        run: |
          cd load-generator
          bin/cleanup-instances --region ${{ secrets.PR_PERF_TEST_AWS_REGION }}