name: Performance Tests

on:
  pull_request:
    branches: [main]

jobs:
  aws-perf-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r verifiers/requirements.txt

      - name: Configure AWS credentials
        id: aws-creds
        continue-on-error: true
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.PR_PERF_TEST_AWS_ROLE_ARN }}
          aws-region: ${{ secrets.PR_PERF_TEST_AWS_REGION }}
          mask-aws-account-id: true

      - name: Run Performance tests on EC2 instances
        if: steps.aws-creds.outcome == 'success'
        run: |
          python3 verifiers/run_performance_tests.py