name: Update Performance Results

on:
  push:
    branches: [main]

jobs:
  update-baselines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for Latest PR performance results
        id: check-results
        run: |
          # Extract the latest PR number
          PR_NUM=$(git log -30 --pretty=format:"%s" | grep -o '#[0-9]\+' | head -1 | tr -d '#' || echo "")
          echo "pr_number=$PR_NUM" >> $GITHUB_OUTPUT

      - name: Find Latest PR workflow run
        if: steps.check-results.outputs.pr_number != ''
        id: find-run
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = '${{ steps.check-results.outputs.pr_number }}';

            // Get the PR branch name
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const prBranch = pr.data.head.ref;

            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'load-tests.yml',
              status: 'completed'
            });

            // Get latest run by branch name
            const prRun = runs.data.workflow_runs.find(run => {
              return run.event === 'pull_request' && run.head_branch === prBranch;
            });

            if (prRun) {
              core.setOutput('run_id', prRun.id);
              core.setOutput('found', 'true');
            } else {
              core.setOutput('found', 'false');
            }

      - name: Download Latest PR performance results
        if: steps.find-run.outputs.found == 'true'
        uses: actions/download-artifact@v4
        with:
          name: performance-results-pr-${{ steps.check-results.outputs.pr_number }}
          path: load-generator/new-results/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.find-run.outputs.run_id }}

      - name: Update baseline reports
        if: steps.find-run.outputs.found == 'true'
        run: |
          PR_NUM=${{ steps.check-results.outputs.pr_number }}

          # Move new reports to baseline location
          if [[ -d "load-generator/new-results" ]] && [[ -n "$(ls -A load-generator/new-results 2>/dev/null)" ]]; then
            mkdir -p load-generator/baseline-reports
            cp load-generator/new-results/*.json load-generator/baseline-reports/ 2>/dev/null || true

            # Configure git
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            # Commit baseline updates
            if [[ -n "$(ls -A load-generator/baseline-reports 2>/dev/null)" ]]; then
              git add load-generator/baseline-reports/
              git commit -m "Update performance baselines from PR #$PR_NUM"
              git push
            fi
          fi